package com.recorda.admin.users.event.model;

/**
 * Handles event messages to be sent to Kafka topics
 *
 * This message contains information below :
 *
 * <ul>
 *   <li>resource : the resource concerned by the message (e.g: a User)</li>
 *   <li>id : an id of the resource</li>
 *   <li>source : type of source that published the messae (REST, SOAP, ...)</li>
 *   <li>type : type of interaction regarding the source (e.g: for REST source, HTTP verbs)</li>
 *   <li>content : full payload (e.g: for REST source, the JSON body)</li>
 * </ul>
 *
 */
public class Message<PAYLOAD, TYPE> {

    /** Concerned resource */
    String resource;

    /** Resource unique id */
    String id;

    /** Event source */
    EventSource source;

    /** Event type generated by the source */
    TYPE type;

    /** Payload */
    PAYLOAD payload;

    public EventSource getSource() {
        return source;
    }

    public void setSource(EventSource source) {
        this.source = source;
    }

    public TYPE getType() {
        return type;
    }

    public void setType(TYPE type) {
        this.type = type;
    }

    public PAYLOAD getPayload() {
        return payload;
    }

    public void setPayload(PAYLOAD PAYLOAD) {
        this.payload = PAYLOAD;
    }

    public String getResource() {
        return resource;
    }

    public void setResource(String resource) {
        this.resource = resource;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}
