# Tomcat server configuration
server:
  port: 8081
  servlet:
    contextPath: /recorda/admin
  error:
    include-message: always

# MongoDB application configuration
mongodb:
  users:
    collection: users

# MongoDB server configuration
spring:
  data:
    mongodb:
      database: recardo
      port: 27017
      host: localhost

# i18n configuration
i18n:
  locale: fr

# APIs
api:
  ipapi:
    uri: https://ipapi.co