# Tomcat server configuration
server:
  port: 8081
  servlet:
    contextPath: /recorda/admin
  error:
    include-message: always


# Spring fwk configurations
spring:
  # MongoDB server configuration
  data:
    mongodb:
      database: recardo
      port: 27017
      host: localhost
  # Kafka server configuration
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


# MongoDB application configuration
mongodb:
  users:
    collection: users

# Kafka application configuration
kafka:
  users:
    topic: recardo-users

# i18n application configuration
i18n:
  locale: fr

# APIs
api:
  ipapi:
    uri: https://ipapi.co