# Tomcat server configuration
server:
  port: 8081
  servlet:
    contextPath: /recorda/admin

# MongoDB application configuration
mongodb:
  users:
    collection: users

# MongoDB server configuration
spring:
  data:
    mongodb:
      database: recardo
      port: 27017
      host: localhost