version: '3'

services:
  mongodb:
    image: mongo
    container_name: recardo-mongo
    ports:
      - "27017:27017"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: recardo-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: recardo-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "recardo-users:1:1"
